# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artfin/Desktop/repos/manolopoulos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artfin/Desktop/repos/manolopoulos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artfin/Desktop/repos/manolopoulos/CMakeFiles /home/artfin/Desktop/repos/manolopoulos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artfin/Desktop/repos/manolopoulos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named log_derivative

# Build rule for target.
log_derivative: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log_derivative
.PHONY : log_derivative

# fast build rule for target.
log_derivative/fast:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/build
.PHONY : log_derivative/fast

log.o: log.cpp.o

.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i

.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s

.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/log.cpp.s
.PHONY : log.cpp.s

log_derivative.o: log_derivative.cpp.o

.PHONY : log_derivative.o

# target to build an object file
log_derivative.cpp.o:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/log_derivative.cpp.o
.PHONY : log_derivative.cpp.o

log_derivative.i: log_derivative.cpp.i

.PHONY : log_derivative.i

# target to preprocess a source file
log_derivative.cpp.i:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/log_derivative.cpp.i
.PHONY : log_derivative.cpp.i

log_derivative.s: log_derivative.cpp.s

.PHONY : log_derivative.s

# target to generate assembly for a file
log_derivative.cpp.s:
	$(MAKE) -f CMakeFiles/log_derivative.dir/build.make CMakeFiles/log_derivative.dir/log_derivative.cpp.s
.PHONY : log_derivative.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... log_derivative"
	@echo "... edit_cache"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... log_derivative.o"
	@echo "... log_derivative.i"
	@echo "... log_derivative.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

